onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {Test Cases}
add wave -noupdate -color Gold -radix decimal -subitemconfig {{/tb_adder_16bit/tb_test_case_num[31]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[30]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[29]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[28]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[27]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[26]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[25]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[24]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[23]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[22]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[21]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[20]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[19]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[18]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[17]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[16]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[15]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[14]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[13]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[12]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[11]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[10]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[9]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[8]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[7]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[6]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[5]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[4]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[3]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[2]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[1]} {-color Gold} {/tb_adder_16bit/tb_test_case_num[0]} {-color Gold}} /tb_adder_16bit/tb_test_case_num
add wave -noupdate /tb_adder_16bit/tb_test_case
add wave -noupdate /tb_adder_16bit/tb_test_case_stage
add wave -noupdate -color Gold -radix hexadecimal /tb_adder_16bit/tb_test_case_err
add wave -noupdate -divider Inputs
add wave -noupdate -expand -group Inputs -color {Spring Green} -radix hexadecimal -childformat {{{/tb_adder_16bit/tb_a[15]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[14]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[13]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[12]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[11]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[10]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[9]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[8]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[7]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[6]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[5]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[4]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[3]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[2]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[1]} -radix hexadecimal} {{/tb_adder_16bit/tb_a[0]} -radix hexadecimal}} -subitemconfig {{/tb_adder_16bit/tb_a[15]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[14]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[13]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[12]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[11]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[10]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[9]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[8]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[7]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[6]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[5]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[4]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[3]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[2]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[1]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_a[0]} {-color {Spring Green} -radix hexadecimal}} /tb_adder_16bit/tb_a
add wave -noupdate -expand -group Inputs -color {Spring Green} -radix hexadecimal -childformat {{{/tb_adder_16bit/tb_b[15]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[14]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[13]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[12]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[11]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[10]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[9]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[8]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[7]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[6]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[5]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[4]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[3]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[2]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[1]} -radix hexadecimal} {{/tb_adder_16bit/tb_b[0]} -radix hexadecimal}} -subitemconfig {{/tb_adder_16bit/tb_b[15]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[14]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[13]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[12]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[11]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[10]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[9]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[8]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[7]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[6]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[5]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[4]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[3]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[2]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[1]} {-color {Spring Green} -radix hexadecimal} {/tb_adder_16bit/tb_b[0]} {-color {Spring Green} -radix hexadecimal}} /tb_adder_16bit/tb_b
add wave -noupdate -expand -group Inputs -color {Spring Green} -radix hexadecimal /tb_adder_16bit/tb_carry_in
add wave -noupdate -divider {DUT Signals}
add wave -noupdate -expand -group Overflow -color Red -radix hexadecimal /tb_adder_16bit/tb_overflow
add wave -noupdate -expand -group Overflow -color Red -radix hexadecimal /tb_adder_16bit/tb_expected_overflow
add wave -noupdate -expand -group Sum -color {Cornflower Blue} -radix hexadecimal /tb_adder_16bit/tb_sum
add wave -noupdate -expand -group Sum -color {Cornflower Blue} -radix hexadecimal -childformat {{{/tb_adder_16bit/tb_expected_sum[15]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[14]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[13]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[12]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[11]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[10]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[9]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[8]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[7]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[6]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[5]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[4]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[3]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[2]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[1]} -radix hexadecimal} {{/tb_adder_16bit/tb_expected_sum[0]} -radix hexadecimal}} -subitemconfig {{/tb_adder_16bit/tb_expected_sum[15]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[14]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[13]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[12]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[11]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[10]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[9]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[8]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[7]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[6]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[5]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[4]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[3]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[2]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[1]} {-color {Cornflower Blue} -radix hexadecimal} {/tb_adder_16bit/tb_expected_sum[0]} {-color {Cornflower Blue} -radix hexadecimal}} /tb_adder_16bit/tb_expected_sum
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {53550 ps}
